=== folio-org/mod-data-export/src/main/resources/swagger.api/schemas/profiles/jobProfile.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Job profile",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "description": "Unique identifier",
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "description": "Job Profile name",
      "type": "string"
    },
    "default" : {
      "description": "Is default job profile",
      "type": "boolean",
      "default": false,
      "readonly": true
    },
    "destination": {
      "description": "Final destination place where to send file",
      "type": "string"
    },
    "description": {
      "description": "Job Profile description",
      "type": "string"
    },
    "userInfo": {
      "description": "First name, last name and username of the user, who updated the Job Profile",
      "type": "object",
      "$ref": "userInfo.json"
    },
    "mappingProfileId": {
      "description": "Associated mapping profile id",
      "type": "string",
      "format": "uuid"
    },
    "protocol": {
      "description": "TCP/IP settings",
      "type": "object",
      "$ref": "protocol.json"
    },
    "metadata": {
      "description": "Metadata provided by the server",
      "type": "object",
      "$ref": "../metadata.json",
      "readonly": true
    }
  },
  "required": [
    "name",
    "mappingProfileId"
  ]
}

=== folio-org/mod-data-export/src/main/resources/data/job-profiles/default_deleted_authority_job_profile.json
{
  "id": "2c9be114-6d35-4408-adac-9ead35f51a27",
  "name": "Export deleted authority records job profile",
  "default" : true,
  "destination": "fileSystem",
  "description": "Export deleted authority records job profile",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "mappingProfileId": "5d636597-a59d-4391-a270-4e79d5ba70e3",
  "metadata":{
    "createdDate":"2024-03-14T00:00:00Z",
    "createdByUserId":"00000000-0000-0000-0000-000000000000",
    "createdByUsername":"system_process",
    "updatedDate":"2024-03-14T00:00:00Z",
    "updatedByUserId":"00000000-0000-0000-0000-000000000000",
    "updatedByUsername":"system_process"
  }
}

=== folio-org/mod-data-export/src/main/resources/data/job-profiles/default_authority_job_profile.json
{
  "id": "56944b1c-f3f9-475b-bed0-7387c33620ce",
  "name": "Default authority export job profile",
  "default" : true,
  "destination": "fileSystem",
  "description": "Default authority job profile",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "mappingProfileId": "5d636597-a59d-4391-a270-4e79d5ba70e3",
  "metadata":{
    "createdDate":"2020-07-28T00:00:00Z",
    "createdByUserId":"00000000-0000-0000-0000-000000000000",
    "createdByUsername":"system_process",
    "updatedDate":"2020-07-28T00:00:00Z",
    "updatedByUserId":"00000000-0000-0000-0000-000000000000",
    "updatedByUsername":"system_process"
  }
}

=== folio-org/mod-data-export/src/main/resources/data/job-profiles/default_linked_data_job_profile.json
{
  "id": "42ca0945-f66c-4bc1-8d1a-7aa8b2e4483a",
  "name": "Default linked data export job profile",
  "default" : true,
  "destination": "fileSystem",
  "description": "Default linked data job profile",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "mappingProfileId": "f8b400da-6a0c-4058-be10-cece93265c32",
  "metadata":{
    "createdDate":"2025-09-24T00:00:00Z",
    "createdByUserId":"00000000-0000-0000-0000-000000000000",
    "createdByUsername":"system_process",
    "updatedDate":"2025-09-24T00:00:00Z",
    "updatedByUserId":"00000000-0000-0000-0000-000000000000",
    "updatedByUsername":"system_process"
  }
}

=== folio-org/mod-data-export/src/main/resources/data/job-profiles/default_holdings_job_profile.json
{
  "id": "5e9835fc-0e51-44c8-8a47-f7b8fce35da7",
  "name": "Default holdings export job profile",
  "default" : true,
  "destination": "fileSystem",
  "description": "Default holdings job profile",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "mappingProfileId": "1ef7d0ac-f0a8-42b5-bbbb-c7e249009c13",
  "metadata":{
    "createdDate":"2020-07-28T00:00:00Z",
    "createdByUserId":"00000000-0000-0000-0000-000000000000",
    "createdByUsername":"system_process",
    "updatedDate":"2020-07-28T00:00:00Z",
    "updatedByUserId":"00000000-0000-0000-0000-000000000000",
    "updatedByUsername":"system_process"
  }
}
