=== folio-org/mod-data-export/src/main/resources/swagger.api/schemas/profiles/mappingProfile.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Mapping Profile schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "description": "Unique identifier",
      "type": "string",
      "format": "uuid"
    },
    "name": {
      "description": "Mapping Profile name",
      "type": "string"
    },
    "default" : {
      "description": "Is default mapping profile",
      "type": "boolean",
      "default": false,
      "readonly": true
    },
    "description": {
      "description": "Mapping Profile description",
      "type": "string"
    },
    "recordTypes": {
      "description": "Mapping Profile records type",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "recordTypes.json"
      }
    },
    "transformations": {
      "description": "List of mapping profile transformations",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "transformations.json"
      }
    },
    "userInfo": {
      "description": "First name, last name and username of the user, who updated the Mapping Profile",
      "type": "object",
      "$ref": "userInfo.json"
    },
    "outputFormat": {
      "description": "Mapping Profile output format",
      "type": "string",
      "enum": [
        "MARC"
      ]
    },
    "metadata": {
      "description": "Metadata provided by the server",
      "type": "object",
      "$ref": "../metadata.json",
      "readonly": true
    }
  },
  "required": [
    "name",
    "recordTypes"
  ]
}

=== folio-org/mod-data-export/src/main/resources/data/mapping-profiles/default_holdings_mapping_profile.json
{
  "id": "1ef7d0ac-f0a8-42b5-bbbb-c7e249009c13",
  "name": "Default holdings mapping profile",
  "default" : true,
  "description": "Default mapping profile for MARC for holdings record",
  "recordTypes": [
    "HOLDINGS"
  ],
  "outputFormat": "MARC",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "metadata":{
    "createdDate":"2020-07-28T00:00:00Z",
    "createdByUserId":"00000000-0000-0000-0000-000000000000",
    "createdByUsername":"system_process",
    "updatedDate":"2020-07-28T00:00:00Z",
    "updatedByUserId":"00000000-0000-0000-0000-000000000000",
    "updatedByUsername":"system_process"
  }
}

=== folio-org/mod-data-export/src/main/resources/swagger.api/examples/profiles/mappingProfile.json
{
  "id": "3798f546-7afb-11ea-bc55-0242ac130003",
  "name": "Mapping profile",
  "description": "Mapping profile description",
  "recordTypes": [
    "INSTANCE"
  ],
  "outputFormat": "MARC",
  "transformations": [
    {
      "fieldId": "electronicAccess.linkText",
      "path": "Json path for electronicAccess[*].linkText",
      "transformation": "001",
      "enabled": true,
      "recordType": "INSTANCE"
    }
  ],
  "userInfo": {
    "firstName": "User",
    "lastName": "User",
    "userName": "@username"
  },
  "metadata": {
    "createdDate": "2019-07-22T11:22:07Z",
    "createdByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "createdByUsername": "janedoeuser",
    "updatedDate": "2019-07-27T13:28:54Z",
    "updatedByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "updatedByUsername": ""
  }
}

=== folio-org/mod-data-export/src/main/resources/data/mapping-profiles/default_authority_mapping_profile.json
{
  "id": "5d636597-a59d-4391-a270-4e79d5ba70e3",
  "name": "Default authority mapping profile",
  "default" : true,
  "description": "Default authority profile for MARC for authority record",
  "recordTypes": [
    "AUTHORITY"
  ],
  "outputFormat": "MARC",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "metadata":{
    "createdDate":"2020-07-28T00:00:00Z",
    "createdByUserId":"00000000-0000-0000-0000-000000000000",
    "createdByUsername":"system_process",
    "updatedDate":"2020-07-28T00:00:00Z",
    "updatedByUserId":"00000000-0000-0000-0000-000000000000",
    "updatedByUsername":"system_process"
  }
}

=== folio-org/mod-data-export/src/main/resources/data/mappingProfiles/defaultMappingProfiles.json
{
  "id": "25d81cbe-9686-11ea-bb37-0242ac130002",
  "name": "Default instance mapping profile",
  "description": "Default mapping profile for the inventory instance record",
  "recordTypes": [
    "INSTANCE"
  ],
  "outputFormat": "MARC",
  "userInfo": {
    "firstName": "DIKU",
    "lastName": "ADMINISTRATOR",
    "userName": "diku_admin"
  },
  "metadata": {
    "createdDate": "2020-05-15T09:39:13.659+0000",
    "createdByUserId": "08d3ea27-e4ff-4a26-83e1-d5f86f16495c",
    "updatedDate": "2020-05-15T09:39:13.659+0000",
    "updatedByUserId": "08d3ea27-e4ff-4a26-83e1-d5f86f16495c"
  }
}

=== folio-org/mod-data-export/src/test/resources/endToEndTestFiles/srsMappingProfile.json
{
  "id": "946f57cf-08ac-451b-9ea9-56165b9353d5",
  "name": "IT Mapping profile",
  "description": "Mapping profile for Testing Int Tests",
  "recordTypes": [
    "SRS",
    "HOLDINGS"
  ],
  "outputFormat": "MARC",
  "transformations": [
    {
      "fieldId": "holdings.callnumber",
      "path": "$.holdings[*].callNumber",
      "transformation": "90011$a",
      "enabled": true,
      "recordType": "HOLDINGS"
    }
  ]
}

=== folio-org/mod-data-export/src/test/resources/endToEndTestFiles/mappingProfile.json
{
  "id": "e40d9f2a-ae89-4c77-ace7-c87265288ed3",
  "name": "IT Mapping profile",
  "description": "Mapping profile for Testing Int Tests",
  "recordTypes": [
    "HOLDINGS"
  ],
  "outputFormat": "MARC",
  "transformations": [
    {
      "fieldId": "holdings.callnumber",
      "path": "$.holdings[*].callNumber",
      "transformation": "90011$a",
      "enabled": true,
      "recordType": "HOLDINGS"
    }
  ]
}
