=== folio-org/mod-data-export/ramls/schemas/profiles/jobProfile.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Job profile",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "description": "Unique identifier",
      "type": "string",
      "$ref": "../../raml-util/schemas/uuid.schema"
    },
    "name": {
      "description": "Job Profile name",
      "type": "string"
    },
    "destination": {
      "description": "Final destination place where to send file",
      "type": "string"
    },
    "description": {
      "description": "Job Profile description",
      "type": "string"
    },
    "userInfo": {
      "description": "First name, last name and username of the user, who updated the Job Profile",
      "type": "object",
      "$ref": "userInfo.json"
    },
    "mappingProfileId": {
      "description": "Associated mapping profile id",
      "type": "string",
      "$ref": "../../raml-util/schemas/uuid.schema"
    },
    "protocol": {
      "description": "TCP/IP settings",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "protocol.json"
      }
    },
    "metadata": {
      "description": "Metadata provided by the server",
      "type": "object",
      "$ref": "../../raml-util/schemas/metadata.schema",
      "readonly": true
    }
  },
  "required": [
    "name",
    "mappingProfileId"
  ]
}

=== folio-org/mod-data-export/src/main/resources/data/job-profiles/default_instance_job_profile.json
{
  "id": "6f7f3cd7-9f24-42eb-ae91-91af1cd54d0a",
  "name": "Default instances export job profile",
  "destination": "fileSystem",
  "description": "Default instances export job profile",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "mappingProfileId": "25d81cbe-9686-11ea-bb37-0242ac130002",
  "metadata":{
    "createdDate":"2020-07-28T00:00:00Z",
    "createdByUserId":"00000000-0000-0000-0000-000000000000",
    "createdByUsername":"system_process",
    "updatedDate":"2020-07-28T00:00:00Z",
    "updatedByUserId":"00000000-0000-0000-0000-000000000000",
    "updatedByUsername":"system_process"
  }
}

=== folio-org/mod-data-export/src/main/resources/swagger.api/examples/profiles/jobProfile.json
{
  "id": "448ae575-daec-49c1-8041-d64c8ed8e5b1",
  "name": "job profile name",
  "destination": "fileSystem",
  "description": "Job profile description",
  "userInfo": {
    "firstName": "DIKU",
    "lastName": "ADMINISTRATOR",
    "userName": "diku_admin"
  },
  "mappingProfileId": "3798f546-7afb-11ea-bc55-0242ac130003",
  "metadata": {
    "createdDate": "2019-07-22T11:22:07Z",
    "createdByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "createdByUsername": "janedoeuser",
    "updatedDate": "2019-07-27T13:28:54Z",
    "updatedByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "updatedByUsername": ""
  }
}

=== folio-org/mod-data-export/src/main/resources/data/jobProfiles/defaultJobProfiles.json
{
  "id": "19c33d10-99d2-11ea-bb37-0242ac130002",
  "name": "Default job profile",
  "destination": "fileSystem",
  "description": "Default job profile",
  "userInfo": {
    "firstName": "System",
    "lastName": "Process",
    "userName": "system_process"
  },
  "mappingProfileId": "25d81cbe-9686-11ea-bb37-0242ac130002",
  "metadata": {
    "createdDate": "2019-07-22T11:22:07Z",
    "updatedDate": "2019-07-27T13:28:54Z"
  }
}
