=== folio-org/mod-data-export/src/main/resources/swagger.api/schemas/exportRequest.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Necessary data to start export process",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "fileDefinitionId": {
      "description": "File definition id",
      "type": "string",
      "format": "uuid"
    },
    "jobProfileId": {
      "description": "Related Job profile id",
      "type": "string",
      "format": "uuid"
    },
    "recordType": {
      "description": "Defines a type of records to search by criteria or UUIDs",
      "type": "string",
      "enum": [
        "INSTANCE",
        "HOLDINGS",
        "ITEM",
        "AUTHORITY"
      ]
    },
    "idType": {
      "description": "Type of provided uuids",
      "type": "string",
      "enum": [
        "instance",
        "holding",
        "authority"
      ],
      "default": "instance"
    },
    "all": {
      "description": "True if all IDs of idType need to be exported, otherwise false",
      "type": "boolean",
      "default": false
    },
    "quick": {
      "description": "True if quick export, otherwise false",
      "type": "boolean",
      "default": false
    },
    "deletedRecords": {
      "description": "True if need to include deleted records, otherwise false",
      "type": "boolean",
      "default": true
    },
    "deletedMarcIds": {
      "description": "True if need to include DELETED state",
      "type": "boolean",
      "default": false
    },
    "suppressedFromDiscovery": {
      "description": "True if need to include suppressed from discovery records, otherwise false",
      "type": "boolean",
      "default": false
    },
    "lastSlice": {
      "description": "True if within the current export the current slice from ID to ID is the last one",
      "type": "boolean",
      "default": false
    },
    "lastExport": {
      "description": "True the current export is the last one",
      "type": "boolean",
      "default": false
    },
    "metadata": {
      "description": "Meta information ",
      "type": "object",
      "$ref": "metadata.json"
    }
  },
  "required": [
    "fileDefinitionId",
    "jobProfileId",
    "idType"
  ]
}

=== folio-org/mod-data-export/src/main/resources/swagger.api/examples/exportRequest.json
{
  "fileDefinitionId": "e5f54eb6-6d11-11ea-bc55-0242ac130003",
  "jobProfileId": "2fd2bf30-9d03-4f7e-9393-df55eaef2c2f",
  "idType":"instance",
  "recordType": "INSTANCE",
  "metadata": {
    "createdDate": "2019-07-22T11:22:07Z",
    "createdByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "createdByUsername": "janedoeuser",
    "updatedDate": "2019-07-27T13:28:54Z",
    "updatedByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "updatedByUsername": ""
  }
}
