=== folio-org/mod-data-export/src/main/resources/swagger.api/schemas/fileDefinition.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "File definition",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": {
      "description": "UUID of this File Definition",
      "type": "string",
      "format": "uuid"
    },
    "fileName": {
      "description": "File name",
      "type": "string"
    },
    "jobExecutionId": {
      "description": "Job execution id",
      "type": "string",
      "format": "uuid"
    },
    "sourcePath": {
      "description": "Path to the file",
      "type": "string"
    },
    "status": {
      "description": "Status of file upload",
      "type": "string",
      "enum": [
        "NEW",
        "IN_PROGRESS",
        "COMPLETED",
        "ERROR"
      ]
    },
    "size": {
      "description": "Size of the file in Kbyte",
      "type": "integer"
    },
    "uploadFormat": {
      "description": "Format of upload file",
      "type": "string",
      "enum": [
        "csv",
        "cql"
      ],
      "default": "csv"
    },
    "metadata": {
      "description": "Meta information ",
      "type": "object",
      "$ref": "metadata.json"
    }
  },
  "required": [
    "fileName"
  ]
}

=== folio-org/mod-data-export/src/main/resources/swagger.api/examples/fileDefinition.json
{
   "id":"88dfac11-1caf-4470-9ad1-d533f6360bdd",
   "fileName":"marc.csv",
   "status":"COMPLETED",
   "size" : 200,
   "uploadFormat": "csv",
   "metadata":
    {
     "createdDate": "2019-07-22T11:22:07Z",
     "createdByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
     "createdByUsername": "janedoeuser",
     "updatedDate": "2019-07-27T13:28:54Z",
     "updatedByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
     "updatedByUsername": ""
   }
}
