=== folio-org/mod-data-export/src/main/resources/swagger.api/schemas/quickExportRequest.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Necessary data to start export process from inventory",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "jobProfileId": {
      "description": "Job profile id to be used for export",
      "type": "string",
      "format": "uuid"
    },
    "criteria": {
      "description": "CQL query for records search",
      "type": "string"
    },
    "uuids": {
      "description": "List of UUIDs of records to export",
      "type": "array",
      "items": {
        "type": "string",
        "format": "uuid"
      }
    },
    "type": {
      "description": "Defines a type of searching the records: by UUIDs or CQL query",
      "type": "string",
      "enum": [
        "cql",
        "uuid"
      ]
    },
    "recordType": {
      "description": "Defines a type of records to search by criteria or UUIDs",
      "type": "string",
      "enum": [
        "INSTANCE",
        "HOLDINGS",
        "ITEM",
        "AUTHORITY"
      ]
    },
    "fileName": {
      "description": "Name of the generated marc file",
      "type": "string"
    },
    "metadata": {
      "description": "Meta information ",
      "type": "object",
      "$ref": "metadata.json"
    }
  },
  "required": [
    "type",
    "recordType"
  ]
}

=== folio-org/mod-data-export/src/main/resources/swagger.api/examples/quickExportRequest.json
{
  "jobProfileId": "2fd2bf30-9d03-4f7e-9393-df55eaef2c2f",
  "criteria": "(source==\"MARC\" and discoverySuppress==\"true\")",
  "uuids": [],
  "type": "cql",
  "recordType": "INSTANCE",
  "metadata": {
    "createdDate": "2019-07-22T11:22:07Z",
    "createdByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "createdByUsername": "janedoeuser",
    "updatedDate": "2019-07-27T13:28:54Z",
    "updatedByUserId": "dee12548-9cee-45fa-bbae-675c1cc0ce3b",
    "updatedByUsername": ""
  }
}
